server:
  port: ${PORT:8080}
#logging:
#  level:
#    root: debug
management:
  endpoints:
    web:
      expose: "*"
      cors.allowed-origins: "*"
      cors.allowed-methods: GET,POST,PUT,DELETE,HEAD
spring:
  application:
    name: ui-app
  thymeleaf:
#    check-template: false
    reactive:
      max-chunk-size: 8192

app:
  cassandraApiUrl: ${CASSANDRA_API_URL:http://localhost:8081}
  streamApiUrl: ${STREAM_API_URL:http://localhost:8082}
  loggger:
    bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic: applogs

---
spring:
  profiles: docker

app:
  loggger:
    bootstrapServers: kafka:9092

