global:
  resolve_timeout: 5m

  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: $GMAIL_ACCOUNT

route:
  receiver: 'default'

receivers:
  - name: 'default'
    email_configs:
    - to: $GMAIL_ACCOUNT
      from: $GMAIL_ACCOUNT
      smarthost: smtp.gmail.com:587
      auth_username: "$GMAIL_ACCOUNT"
      auth_identity: "$GMAIL_ACCOUNT"
      auth_password: "$GMAIL_AUTH_TOKEN"
